#!/usr/bin/python3
import os
import sys


os.system("docker run --privileged -i \
    -v /proc:/proc -v ${PWD}:/working_dir \
    -w /working_dir \
    debian:latest \
    /bin/bash -s etc/terraform.conf < build.sh")

